export const GET_STATS = 'GET_STATS';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_ERROR = 'TOGGLE_ERROR';
export const TOGGLE_SUGGESTIONS_LOADING = 'TOGGLE_SUGGESTIONS_LOADING';