export const GET_BOOK_ABSTRACTS = 'GET_BOOK_ABSTRACTS';
export const GET_ABSTRACT_DETAIL = 'GET_ABSTRACT_DETAIL';
export const RESET_ABSTRACT_DETAIL = 'RESET_ABSTRACT_DETAIL';
export const CUSTOM_URL_ABSTRACTS = 'CUSTOM_URL_ABSTRACTS';